# Generated by Django 5.0.6 on 2024-06-16 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Album_Name', models.CharField(max_length=50)),
                ('Album_release_date', models.DateField()),
                ('Rating', models.IntegerField()),
                ('musician_model', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='musician.musician')),
            ],
        ),
    ]
